(cl:defpackage Kinefly-srv
  (:use )
  (:export
   "SRVFLOAT32LIST"
   "<SRVFLOAT32LIST-REQUEST>"
   "SRVFLOAT32LIST-REQUEST"
   "<SRVFLOAT32LIST-RESPONSE>"
   "SRVFLOAT32LIST-RESPONSE"
   "SRVTIPDATA"
   "<SRVTIPDATA-REQUEST>"
   "SRVTIPDATA-REQUEST"
   "<SRVTIPDATA-RESPONSE>"
   "SRVTIPDATA-RESPONSE"
   "SRVTRACKERDATA"
   "<SRVTRACKERDATA-REQUEST>"
   "SRVTRACKERDATA-REQUEST"
   "<SRVTRACKERDATA-RESPONSE>"
   "SRVTRACKERDATA-RESPONSE"
   "SRVWINGDATA"
   "<SRVWINGDATA-REQUEST>"
   "SRVWINGDATA-REQUEST"
   "<SRVWINGDATA-RESPONSE>"
   "SRVWINGDATA-RESPONSE"
  ))

