// Generated by gencpp from file Kinefly/MsgFlystate.msg
// DO NOT EDIT!


#ifndef KINEFLY_MESSAGE_MSGFLYSTATE_H
#define KINEFLY_MESSAGE_MSGFLYSTATE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <Kinefly/MsgState.h>
#include <Kinefly/MsgState.h>
#include <Kinefly/MsgState.h>
#include <Kinefly/MsgState.h>
#include <Kinefly/MsgState.h>

namespace Kinefly
{
template <class ContainerAllocator>
struct MsgFlystate_
{
  typedef MsgFlystate_<ContainerAllocator> Type;

  MsgFlystate_()
    : header()
    , head()
    , abdomen()
    , left()
    , right()
    , aux()  {
    }
  MsgFlystate_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , head(_alloc)
    , abdomen(_alloc)
    , left(_alloc)
    , right(_alloc)
    , aux(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef  ::Kinefly::MsgState_<ContainerAllocator>  _head_type;
  _head_type head;

   typedef  ::Kinefly::MsgState_<ContainerAllocator>  _abdomen_type;
  _abdomen_type abdomen;

   typedef  ::Kinefly::MsgState_<ContainerAllocator>  _left_type;
  _left_type left;

   typedef  ::Kinefly::MsgState_<ContainerAllocator>  _right_type;
  _right_type right;

   typedef  ::Kinefly::MsgState_<ContainerAllocator>  _aux_type;
  _aux_type aux;




  typedef boost::shared_ptr< ::Kinefly::MsgFlystate_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::Kinefly::MsgFlystate_<ContainerAllocator> const> ConstPtr;

}; // struct MsgFlystate_

typedef ::Kinefly::MsgFlystate_<std::allocator<void> > MsgFlystate;

typedef boost::shared_ptr< ::Kinefly::MsgFlystate > MsgFlystatePtr;
typedef boost::shared_ptr< ::Kinefly::MsgFlystate const> MsgFlystateConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::Kinefly::MsgFlystate_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::Kinefly::MsgFlystate_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace Kinefly

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'Kinefly': ['/home/nvidia/kinefly_catkin_ws/src/Kinefly/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::Kinefly::MsgFlystate_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::Kinefly::MsgFlystate_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::Kinefly::MsgFlystate_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::Kinefly::MsgFlystate_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::Kinefly::MsgFlystate_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::Kinefly::MsgFlystate_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::Kinefly::MsgFlystate_<ContainerAllocator> >
{
  static const char* value()
  {
    return "805e203f09167a53749bb837921c9afe";
  }

  static const char* value(const ::Kinefly::MsgFlystate_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x805e203f09167a53ULL;
  static const uint64_t static_value2 = 0x749bb837921c9afeULL;
};

template<class ContainerAllocator>
struct DataType< ::Kinefly::MsgFlystate_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Kinefly/MsgFlystate";
  }

  static const char* value(const ::Kinefly::MsgFlystate_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::Kinefly::MsgFlystate_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header    header\n\
MsgState  head\n\
MsgState  abdomen\n\
MsgState  left\n\
MsgState  right\n\
MsgState  aux\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: Kinefly/MsgState\n\
float64[] angles\n\
float64[] gradients\n\
float64[] radii\n\
float64 freq\n\
float64 intensity\n\
";
  }

  static const char* value(const ::Kinefly::MsgFlystate_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::Kinefly::MsgFlystate_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.head);
      stream.next(m.abdomen);
      stream.next(m.left);
      stream.next(m.right);
      stream.next(m.aux);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MsgFlystate_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::Kinefly::MsgFlystate_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::Kinefly::MsgFlystate_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "head: ";
    s << std::endl;
    Printer< ::Kinefly::MsgState_<ContainerAllocator> >::stream(s, indent + "  ", v.head);
    s << indent << "abdomen: ";
    s << std::endl;
    Printer< ::Kinefly::MsgState_<ContainerAllocator> >::stream(s, indent + "  ", v.abdomen);
    s << indent << "left: ";
    s << std::endl;
    Printer< ::Kinefly::MsgState_<ContainerAllocator> >::stream(s, indent + "  ", v.left);
    s << indent << "right: ";
    s << std::endl;
    Printer< ::Kinefly::MsgState_<ContainerAllocator> >::stream(s, indent + "  ", v.right);
    s << indent << "aux: ";
    s << std::endl;
    Printer< ::Kinefly::MsgState_<ContainerAllocator> >::stream(s, indent + "  ", v.aux);
  }
};

} // namespace message_operations
} // namespace ros

#endif // KINEFLY_MESSAGE_MSGFLYSTATE_H
