// Generated by gencpp from file Kinefly/MsgState.msg
// DO NOT EDIT!


#ifndef KINEFLY_MESSAGE_MSGSTATE_H
#define KINEFLY_MESSAGE_MSGSTATE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace Kinefly
{
template <class ContainerAllocator>
struct MsgState_
{
  typedef MsgState_<ContainerAllocator> Type;

  MsgState_()
    : angles()
    , gradients()
    , radii()
    , freq(0.0)
    , intensity(0.0)  {
    }
  MsgState_(const ContainerAllocator& _alloc)
    : angles(_alloc)
    , gradients(_alloc)
    , radii(_alloc)
    , freq(0.0)
    , intensity(0.0)  {
  (void)_alloc;
    }



   typedef std::vector<double, typename ContainerAllocator::template rebind<double>::other >  _angles_type;
  _angles_type angles;

   typedef std::vector<double, typename ContainerAllocator::template rebind<double>::other >  _gradients_type;
  _gradients_type gradients;

   typedef std::vector<double, typename ContainerAllocator::template rebind<double>::other >  _radii_type;
  _radii_type radii;

   typedef double _freq_type;
  _freq_type freq;

   typedef double _intensity_type;
  _intensity_type intensity;




  typedef boost::shared_ptr< ::Kinefly::MsgState_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::Kinefly::MsgState_<ContainerAllocator> const> ConstPtr;

}; // struct MsgState_

typedef ::Kinefly::MsgState_<std::allocator<void> > MsgState;

typedef boost::shared_ptr< ::Kinefly::MsgState > MsgStatePtr;
typedef boost::shared_ptr< ::Kinefly::MsgState const> MsgStateConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::Kinefly::MsgState_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::Kinefly::MsgState_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace Kinefly

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'Kinefly': ['/home/nvidia/kinefly_catkin_ws/src/Kinefly/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::Kinefly::MsgState_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::Kinefly::MsgState_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::Kinefly::MsgState_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::Kinefly::MsgState_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::Kinefly::MsgState_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::Kinefly::MsgState_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::Kinefly::MsgState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c3756d4b54fc38e1deb413f8fefd8833";
  }

  static const char* value(const ::Kinefly::MsgState_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc3756d4b54fc38e1ULL;
  static const uint64_t static_value2 = 0xdeb413f8fefd8833ULL;
};

template<class ContainerAllocator>
struct DataType< ::Kinefly::MsgState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Kinefly/MsgState";
  }

  static const char* value(const ::Kinefly::MsgState_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::Kinefly::MsgState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64[] angles\n\
float64[] gradients\n\
float64[] radii\n\
float64 freq\n\
float64 intensity\n\
";
  }

  static const char* value(const ::Kinefly::MsgState_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::Kinefly::MsgState_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.angles);
      stream.next(m.gradients);
      stream.next(m.radii);
      stream.next(m.freq);
      stream.next(m.intensity);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MsgState_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::Kinefly::MsgState_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::Kinefly::MsgState_<ContainerAllocator>& v)
  {
    s << indent << "angles[]" << std::endl;
    for (size_t i = 0; i < v.angles.size(); ++i)
    {
      s << indent << "  angles[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.angles[i]);
    }
    s << indent << "gradients[]" << std::endl;
    for (size_t i = 0; i < v.gradients.size(); ++i)
    {
      s << indent << "  gradients[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.gradients[i]);
    }
    s << indent << "radii[]" << std::endl;
    for (size_t i = 0; i < v.radii.size(); ++i)
    {
      s << indent << "  radii[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.radii[i]);
    }
    s << indent << "freq: ";
    Printer<double>::stream(s, indent + "  ", v.freq);
    s << indent << "intensity: ";
    Printer<double>::stream(s, indent + "  ", v.intensity);
  }
};

} // namespace message_operations
} // namespace ros

#endif // KINEFLY_MESSAGE_MSGSTATE_H
