// Generated by gencpp from file Kinefly/SrvFloat32List.msg
// DO NOT EDIT!


#ifndef KINEFLY_MESSAGE_SRVFLOAT32LIST_H
#define KINEFLY_MESSAGE_SRVFLOAT32LIST_H

#include <ros/service_traits.h>


#include <Kinefly/SrvFloat32ListRequest.h>
#include <Kinefly/SrvFloat32ListResponse.h>


namespace Kinefly
{

struct SrvFloat32List
{

typedef SrvFloat32ListRequest Request;
typedef SrvFloat32ListResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SrvFloat32List
} // namespace Kinefly


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::Kinefly::SrvFloat32List > {
  static const char* value()
  {
    return "29b66312516f23f8d8d7a48b07d9378a";
  }

  static const char* value(const ::Kinefly::SrvFloat32List&) { return value(); }
};

template<>
struct DataType< ::Kinefly::SrvFloat32List > {
  static const char* value()
  {
    return "Kinefly/SrvFloat32List";
  }

  static const char* value(const ::Kinefly::SrvFloat32List&) { return value(); }
};


// service_traits::MD5Sum< ::Kinefly::SrvFloat32ListRequest> should match 
// service_traits::MD5Sum< ::Kinefly::SrvFloat32List > 
template<>
struct MD5Sum< ::Kinefly::SrvFloat32ListRequest>
{
  static const char* value()
  {
    return MD5Sum< ::Kinefly::SrvFloat32List >::value();
  }
  static const char* value(const ::Kinefly::SrvFloat32ListRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::Kinefly::SrvFloat32ListRequest> should match 
// service_traits::DataType< ::Kinefly::SrvFloat32List > 
template<>
struct DataType< ::Kinefly::SrvFloat32ListRequest>
{
  static const char* value()
  {
    return DataType< ::Kinefly::SrvFloat32List >::value();
  }
  static const char* value(const ::Kinefly::SrvFloat32ListRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::Kinefly::SrvFloat32ListResponse> should match 
// service_traits::MD5Sum< ::Kinefly::SrvFloat32List > 
template<>
struct MD5Sum< ::Kinefly::SrvFloat32ListResponse>
{
  static const char* value()
  {
    return MD5Sum< ::Kinefly::SrvFloat32List >::value();
  }
  static const char* value(const ::Kinefly::SrvFloat32ListResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::Kinefly::SrvFloat32ListResponse> should match 
// service_traits::DataType< ::Kinefly::SrvFloat32List > 
template<>
struct DataType< ::Kinefly::SrvFloat32ListResponse>
{
  static const char* value()
  {
    return DataType< ::Kinefly::SrvFloat32List >::value();
  }
  static const char* value(const ::Kinefly::SrvFloat32ListResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // KINEFLY_MESSAGE_SRVFLOAT32LIST_H
