// Generated by gencpp from file Kinefly/SrvTipdataRequest.msg
// DO NOT EDIT!


#ifndef KINEFLY_MESSAGE_SRVTIPDATAREQUEST_H
#define KINEFLY_MESSAGE_SRVTIPDATAREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace Kinefly
{
template <class ContainerAllocator>
struct SrvTipdataRequest_
{
  typedef SrvTipdataRequest_<ContainerAllocator> Type;

  SrvTipdataRequest_()
    : query(false)  {
    }
  SrvTipdataRequest_(const ContainerAllocator& _alloc)
    : query(false)  {
  (void)_alloc;
    }



   typedef uint8_t _query_type;
  _query_type query;




  typedef boost::shared_ptr< ::Kinefly::SrvTipdataRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::Kinefly::SrvTipdataRequest_<ContainerAllocator> const> ConstPtr;

}; // struct SrvTipdataRequest_

typedef ::Kinefly::SrvTipdataRequest_<std::allocator<void> > SrvTipdataRequest;

typedef boost::shared_ptr< ::Kinefly::SrvTipdataRequest > SrvTipdataRequestPtr;
typedef boost::shared_ptr< ::Kinefly::SrvTipdataRequest const> SrvTipdataRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::Kinefly::SrvTipdataRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::Kinefly::SrvTipdataRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace Kinefly

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'Kinefly': ['/home/nvidia/kinefly_catkin_ws/src/Kinefly/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::Kinefly::SrvTipdataRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::Kinefly::SrvTipdataRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::Kinefly::SrvTipdataRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::Kinefly::SrvTipdataRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::Kinefly::SrvTipdataRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::Kinefly::SrvTipdataRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::Kinefly::SrvTipdataRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d56f052dde9259c4dd003e064bd410a0";
  }

  static const char* value(const ::Kinefly::SrvTipdataRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd56f052dde9259c4ULL;
  static const uint64_t static_value2 = 0xdd003e064bd410a0ULL;
};

template<class ContainerAllocator>
struct DataType< ::Kinefly::SrvTipdataRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Kinefly/SrvTipdataRequest";
  }

  static const char* value(const ::Kinefly::SrvTipdataRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::Kinefly::SrvTipdataRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool query\n\
";
  }

  static const char* value(const ::Kinefly::SrvTipdataRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::Kinefly::SrvTipdataRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.query);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SrvTipdataRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::Kinefly::SrvTipdataRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::Kinefly::SrvTipdataRequest_<ContainerAllocator>& v)
  {
    s << indent << "query: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.query);
  }
};

} // namespace message_operations
} // namespace ros

#endif // KINEFLY_MESSAGE_SRVTIPDATAREQUEST_H
